plugins {
    id "java-library"
}
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}


dependencies {
    compileOnly libs.lombok
    annotationProcessor libs.lombok

    implementation libs.collections4
    implementation libs.slf4j
    implementation libs.ulid

    testImplementation libs.bundles.test
    testCompileOnly libs.lombok
    testAnnotationProcessor libs.lombok

}