spring.application.name=websocket
spring.threads.virtual.enabled=true
maugame.max-players=${MAU_MAX_PLAYERS:5}
maugame.cheating-enabled=${MAU_CHEATING_ENABLED:false}
maugame.rate-limiter.tokens=20
maugame.rate-limiter.reset-every-seconds=3
logging.level.dev.cerios=debug
logging.level.sql=debug
spring.datasource.url=${DB_URI:jdbc:postgresql://localhost:5432/maugame}
spring.datasource.username=${DB_USER:mauUser}
spring.datasource.password=${DB_PASSWORD:mauUser}
spring.jpa.hibernate.ddl-auto=create-drop