spring.application.name=websocket
spring.threads.virtual.enabled=true
maugame.max-players=${MAU_MAX_PLAYERS:5}
maugame.cheating-enabled=${MAU_CHEATING_ENABLED:false}
maugame.rate-limiter.tokens=20
maugame.rate-limiter.reset-every-seconds=3
logging.level.dev.cerios=debug