[versions]
junit = "5.13.4"
mockito = "5.18.0"
springboot = "3.5.6"
mapstruct = "1.6.3"

[libraries]
junit-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit" }
junit-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit" }
assertj = { module = "org.assertj:assertj-core", version = "3.27.3" }
mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockito" }
mockito-junit = { module = "org.mockito:mockito-junit-jupiter", version.ref = "mockito" }
lombok = { module = "org.projectlombok:lombok", version = "1.18.34" }
ulid = { module = "com.github.f4b6a3:ulid-creator", version = "5.2.3" }
slf4j = { module = "org.slf4j:slf4j-api", version = "2.0.17" }
collections4 = { module = "org.apache.commons:commons-collections4", version = "4.5.0" }
springboot-websocket = { module = "org.springframework.boot:spring-boot-starter-websocket", version.ref = "springboot"}
springboot-test = { module = "org.springframework.boot:spring-boot-starter-test", version.ref = "springboot"}
springboot-validation = { module = "org.springframework.boot:spring-boot-starter-validation", version.ref = "springboot"}
mapstruct = { module = "org.mapstruct:mapstruct", version.ref = "mapstruct"}
mapstruct-processor = { module = "org.mapstruct:mapstruct-processor", version.ref = "mapstruct" }


[bundles]
test = ["junit-api", "junit-engine", "assertj", "mockito-core", "mockito-junit"]

